#!/bin/sh

case "$1" in
	authenticator)
		# Authenticator setup
		mkdir -p /etc/codeforge/authenticator/keys/env
		mkdir -p /etc/codeforge/authenticator/svc_keys
		mkdir -p /var/lib/codeforge/authenticator

		if [ ! -e /etc/codeforge/authenticator/keys/env/authenticator.pr ]
		then
			echo "Generating Authenticator private key"
			m2_keys generate 2048 > /etc/codeforge/authenticator/keys/env/authenticator.pr
			chmod 400 /etc/codeforge/authenticator/keys/env/authenticator.pr
			m2_keys extract_public_key /etc/codeforge/authenticator/keys/env/authenticator.pr > /etc/codeforge/authenticator/svc_keys/authenticator.pb
		fi
		;;
	"")
		exec /bin/sh
		;;
esac

exec "$@"
